Milestone 1
John-Arboleda/TNW-clone-page pull request #1
Opened 2021-02-22 22:03 UTC by John-Arboleda

# Project 2 Milestone 1

2021-02-24 20:09 UTC, Forison requested changes
# Status::Changes Required🛑

## 👋 Team,

#### You have done a good on this on so far, however there are few issues we have to address to get this project approved🤗.

* [x]  Pull Request should made up of a title and and short description of what went down on the branch.

* [ ] Let Complete the cloning of the page by adding all section as it appears on the original page. In this project, you are to replicate the archived version of the website [The Next Web](https://perma.cc/M5ZV-Q2D6).

#### All screen sizes

* [ ] The logo has a link (`a` tag). the logo should be wrapped in `<a>` tags to make, conventionally logo in navigation would redirect you to the home page. for let redirect to "#"

* [ ] Use links (`a` tag) for all the menu options, the hamburger button and the search button.
Let us wrap all menu options, button and hamburger into an `<a>` tags.

* [ ] The header sticks to the top of the screen when the user scrolls down. The header should stick to the top of the page thus, assume a fixed position to remain fixed when scrolling.

#### Tablet
* [ ] Menu and submenu appear on the header, and the hamburger button disappears. Currently the search button also disappear but it shouldn't. it should be at the far right, but no hamburger.

#### Latest Funding section

* [ ] The text excerpt at the bottom, that also has a link (`a` tag). Let us wrap it in an anchor tag.
* [ ] The text(excerpt) moves out of the pink section at mobile screen. Put some padding to the bottom to prevent this bug.
> latest funding tiles element are each wrapped in `<a>` tags.

#### Footer
* [ ] It contains social media icons centered in a `nav` tag, each of them with a link (`a` tag).
Let us wrap it in an anchor tag.

* [ ] Below the social media menu, there is another menu also centered, with a `nav` tag and each option with a link (`a` tag).
Let us wrap footer social media menu and link into anchor tags

#### That is it kindly make the change and submit a re-review💪

#### Happy coding👨‍💻

Addo Forison

2021-02-24 20:23 UTC, Forison reviewed
# Status::Changes Required🛑

## 👋 Team,

#### You have done a good on this on so far, however there are few issues we have to address to get this project approved🤗.

* [x]  Pull Request should made up of a title and and short description of what went down on the branch.

* [ ] Let Complete the cloning of the page by adding all section as it appears on the original page. In this project, the student replicates the archived version of the website [The Next Web](https://perma.cc/M5ZV-Q2D6).

#### All screen sizes

* [x] The logo has a link (`a` tag). the logo should be wrapped in `<a>` tags to make, conventionally logo in navigation would redirect you to the home page. for let redirect to "#"

* [x] Use links (`a` tag) for all the menu options, the hamburger button and the search button
Let us wrap all menu options, button and hamburger into an `<a>` tags

* [x] The header sticks to the top of the screen when the user scrolls down. The header should stick to the top of the page thus, assume a fixed position to remain fixed when scrolling.

#### Mobile

* [ ] There is a hamburger (bars) icon at the rightmost part (next to search icon). T

#### Tablet
* [ ] Menu and submenu appear on the header, and the hamburger button disappears Currently the search button also disappear but it shouldn't. it should be at the far right, but no hamburger.

#### Mobile

All the first 3 articles take the maximum width and are are aligned in one column. 

#### Latest Funding section

* [ ] The text excerpt at the bottom, that also has a link (`a` tag). Let us wrap it in an anchor tag.
* [ ] The text(excerpt) moves out of the pink section at mobile screen. Put some padding to the bottom to prevent this bug.

#### Footer
* [ ] It contains social media icons centered in a `nav` tag, each of them with a link (`a` tag)
Let us wrap it in an anchor tag.

* [ ] Below the social media menu, there is another menu also centered, with a `nav` tag and each option with a link (`a` tag)
Let us wrap footer link into anchor tags

#### That is it kindly make the change and submit a re-review💪

#### Happy coding👨‍💻

Addo Forison

2021-02-24 20:23 UTC, Forison commented on style.css
> +  display: flex;
**[OPTIONAL]**
* [ ] Avoid redefining a same attribute over and over, you define it, in isolation and used wherever you want to. We could declare this as a class on it own. 
`.flex{
display: flex;
}
`

2021-02-25 05:12 UTC, mimipeshy commented
### STATUS :APPROVED :partying_face: 

Hey there  @John-Arboleda and @francisuloko   :wave: :wave:  good job on working on the requested changes. This project is therefore approved. Go ahead and merge. All the best in the next milestones :man_technologist: 

Regards
Peris Ndanu

2021-02-25 14:05 UTC, merged